### ISSUE TITLE
Error derive

### ISSUE THREAD

**Issue by dr-orlovsky** [elichai/derive-wrapper#1]
It's quite common to do

```rust
pub enum CustomError {
    // ...
}

impl std::error::Error for CustomError { }
```

so it will be great to have

```rust
#[derive(Error)]
pub enum CustomError {
    // ...
}
```

I'm still not good with proc macro, otherwise were doing a PR for that...

**Comment by elichai** [comment]
Will do. are you using this library?
I don't quite remember at what stage have I left it so any feedback would be great :)

**Comment by dr-orlovsky** [comment]
I am using the library in each piece of code I write :) It works smoothly

It would be also great to have something like
```rust
#[derive(Error, From)]
enum Error {
    #[derive_from]
    IoError(std::io::Error),
    #[derive_from]
    JoinError(tokio::task::JoinError)
}
```

to automatically generate things like
```rust
impl From<std::io::Error> for Error {
    fn from(err: std::io::Error) -> Self {
        Error::IoError(err)
    }
}
```

**Comment by elichai** [comment]
Done. please tell me if that's what you've wanted :)

**Comment by dr-orlovsky** [comment]
It is, thank you!
