### ISSUE TITLE
Support `Borrow` and `Deref` .

### ISSUE THREAD

**Issue by Jason5Lee** [elichai/derive-wrapper#10]
Especially `Deref` . If a wrapper of `T` implements `Deref<Target=T>` , you can call the method of `T` on the wrapper without any other conversion.

**Comment by dr-orlovsky** [comment]
Btw, if you don't require MSRV<1.41 you can also take a look at https://crates.io/crates/amplify_derive which allows doing `Wrapper` with `Borrow` & `Deref` and much more: https://github.com/LNP-BP/rust-amplify/blob/master/derive/src/wrapper.rs
