### ISSUE TITLE
[WIP] Use case to consider

### ISSUE THREAD

**Issue by dr-orlovsky** [elichai/derive-wrapper#2]
We work on doing ZMQ IPCs in a Rust-DSL way: <https://github.com/LNP-BP/lnpbps/issues/21#issuecomment-611717346>. This will require many `From<zmq::Message>` derives. Once we will standartize the idea, would you be interested in supporting derive macro for that kind of task with this crate?

**Comment by elichai** [comment]
Is this the same as https://github.com/elichai/derive-wrapper/issues/1#issuecomment-609376070? if so I already implemented this

**Comment by dr-orlovsky** [comment]
Oh yes, it seems to be covered by that! Will try, though about Error case due to some reason only...
