### ISSUE TITLE
Further extension for `#[derive_from]` macro

### ISSUE THREAD

**Issue by dr-orlovsky** [elichai/derive-wrapper#3]
The macro works great, it saves a lot of boilerplate code in such cases as error propagation. However there is one use case which is not yet covered by it: if we need to derive enum item from some Error without providing it with the error object as an argument:

https://github.com/LNP-BP/rust-lnpbp/blob/d668307c7c2a7f97f9254a1c43785020abbb201b/src/api/error.rs#L24-L69

And, there may be multiple implementations, like

```rust
#[derive(From)]
enum Error {
     #[derive_from=io::Error,bitcoin::conosensus::encode::Error]
     SerializationError
}
```

Is is possible to implement such thing? I would not say that it is highly critical, but rather just "nice to have"...

**Comment by elichai** [comment]
Hmmm so that would practically just discard the error and produce that empty one instead?
as for syntax, I think `#[derive_from(io::Error,bitcoin::conosensus::encode::Error)]` looks better?

**Comment by dr-orlovsky** [comment]
Well, there are cases where error does not contain any information within; the sample with `io::Error` was bad in this regard. You syntax is better, yep

**Comment by elichai** [comment]
K, Will do that later today

**Comment by elichai** [comment]
hmm so apparently syn only got proper path parsing in version 1.X.X
and I use 0.15 for compatibility reasons, I'll try to work around it

**Comment by dr-orlovsky** [comment]
Much appreciate!

Another case I just had is to convert `core::option::NoneError` into one of error variants. So 
```rust
use core::option::NoneError;

#[derive(From)]
enum Error {
     #[derive_from=NoneError]
     ValueNotFound
}
```

will really help!

**Comment by elichai** [comment]
I'm starting to think that parsing a path in the `Meta` part isn't possible in pre-1.0 syn.
and working around it seems not possible without basically re-implementing syn,
How do you feel about:
```rust
use crate1::error::Error as Crate1Error;
use crate2::error::Error as Crate2Error;

#[derive(From)]
enum Error {
     #[derive_from(Crate1Error, Crate2Error)]
     Other
}
```

**Comment by dr-orlovsky** [comment]
I think this will work for now!

**Comment by elichai** [comment]
Can you please test https://github.com/elichai/derive-wrapper/pull/4? Thanks!

**Comment by dr-orlovsky** [comment]
Works like magic, thank you!

**Comment by elichai** [comment]
Published

**Comment by elichai** [comment]
Can you test https://github.com/elichai/derive-wrapper/pull/5? Thanks!
